name: 01 - Building Blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, harish you started the workflow!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say goodbye # checking for testing github action
        run:
          echo "Goodbye, world!"
          exit 0
      - name: Say goodbye again
        run: echo "Goodbye again, world!"